version: '2'
services:
  zookeeper2:
    mem_limit: 256mb
    image: confluentinc/cp-zookeeper
    container_name: zookeeper2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka2:
    mem_limit: 512mb
    image: confluentinc/cp-kafka
    container_name: kafka2
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092, EXTERNAL://kafka2:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka3:
    mem_limit: 512mb
    image: confluentinc/cp-kafka
    container_name: kafka3
    ports:
      - "9095:9095"
    depends_on:
      - zookeeper2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093, EXTERNAL://kafka3:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9093,EXTERNAL://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
